### ISSUE TITLE
6.2 update crashes game when installed/fails to install

### ISSUE THREAD

**Issue by ryancflowers** [PrincessRTFM/XIVComboPlugin#58]
23:01:32.674 | ERR [LOCALPLUGIN] Error while loading XIV Combo Very Expanded
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVComboVX.Config.UpdateAlerter.checkMessage() in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboVX\Config\UpdateAlerter.cs:line 74
   at XIVComboVX.Plugin..ctor(DalamudPluginInterface pluginInterface) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboVX\Plugin.cs:line 35
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 416
--------------------------------
23:01:32.675 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVComboVX.Config.UpdateAlerter.checkMessage() in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboVX\Config\UpdateAlerter.cs:line 74
   at XIVComboVX.Plugin..ctor(DalamudPluginInterface pluginInterface) in D:\a\XIVComboPlugin\XIVComboPlugin\XIVComboVX\Plugin.cs:line 35
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 416
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 784
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 737
{ } [ Send ]

**Comment by PrincessRTFM** [comment]
I've added a crash guard, but unfortunately the plugin isn't working again yet. It's unable to find an internal piece of the game that it needs to. I'm working on it.

**Comment by PrincessRTFM** [comment]
Fixed it. Plugin is confirmed working again.
